[workspace]
resolver = "2"
members = [
    "mimic-shared",
    "mimic-gen",
    "mimic-apply",
]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }